@echo off
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarEmail\",\"payload\":\"{\\\"destinatario\\\":\\\"user1@email.com\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"GerarRelatorio\",\"payload\":\"{\\\"tipo\\\":\\\"Vendas\\\",\\\"formato\\\":\\\"PDF\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ProcessarPagamento\",\"payload\":\"{\\\"pedidoId\\\":\\\"ped_001\\\",\\\"valor\\\":100.00}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarNotificacao\",\"payload\":\"{\\\"usuarioId\\\":\\\"usr_001\\\",\\\"canal\\\":\\\"push\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ForceError\",\"payload\":\"{\\\"motivo\\\":\\\"teste de falha 1\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarEmail\",\"payload\":\"{\\\"destinatario\\\":\\\"user2@email.com\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"GerarRelatorio\",\"payload\":\"{\\\"tipo\\\":\\\"Mensal\\\",\\\"formato\\\":\\\"Excel\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ProcessarPagamento\",\"payload\":\"{\\\"pedidoId\\\":\\\"ped_002\\\",\\\"valor\\\":250.00}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarNotificacao\",\"payload\":\"{\\\"usuarioId\\\":\\\"usr_002\\\",\\\"canal\\\":\\\"email\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ForceError\",\"payload\":\"{\\\"motivo\\\":\\\"teste de falha 2\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarEmail\",\"payload\":\"{\\\"destinatario\\\":\\\"user3@email.com\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"GerarRelatorio\",\"payload\":\"{\\\"tipo\\\":\\\"Anual\\\",\\\"formato\\\":\\\"PDF\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ProcessarPagamento\",\"payload\":\"{\\\"pedidoId\\\":\\\"ped_003\\\",\\\"valor\\\":750.00}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarNotificacao\",\"payload\":\"{\\\"usuarioId\\\":\\\"usr_003\\\",\\\"canal\\\":\\\"sms\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ForceError\",\"payload\":\"{\\\"motivo\\\":\\\"teste de falha 3\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarEmail\",\"payload\":\"{\\\"destinatario\\\":\\\"user4@email.com\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"GerarRelatorio\",\"payload\":\"{\\\"tipo\\\":\\\"Semanal\\\",\\\"formato\\\":\\\"CSV\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ProcessarPagamento\",\"payload\":\"{\\\"pedidoId\\\":\\\"ped_004\\\",\\\"valor\\\":1200.00}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarNotificacao\",\"payload\":\"{\\\"usuarioId\\\":\\\"usr_004\\\",\\\"canal\\\":\\\"push\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ForceError\",\"payload\":\"{\\\"motivo\\\":\\\"teste de falha 4\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarEmail\",\"payload\":\"{\\\"destinatario\\\":\\\"user5@email.com\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"GerarRelatorio\",\"payload\":\"{\\\"tipo\\\":\\\"Diario\\\",\\\"formato\\\":\\\"PDF\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ProcessarPagamento\",\"payload\":\"{\\\"pedidoId\\\":\\\"ped_005\\\",\\\"valor\\\":89.90}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarNotificacao\",\"payload\":\"{\\\"usuarioId\\\":\\\"usr_005\\\",\\\"canal\\\":\\\"push\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ForceError\",\"payload\":\"{\\\"motivo\\\":\\\"teste de falha 5\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarEmail\",\"payload\":\"{\\\"destinatario\\\":\\\"user6@email.com\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"GerarRelatorio\",\"payload\":\"{\\\"tipo\\\":\\\"Vendas\\\",\\\"formato\\\":\\\"Excel\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ProcessarPagamento\",\"payload\":\"{\\\"pedidoId\\\":\\\"ped_006\\\",\\\"valor\\\":450.00}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarNotificacao\",\"payload\":\"{\\\"usuarioId\\\":\\\"usr_006\\\",\\\"canal\\\":\\\"email\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ForceError\",\"payload\":\"{\\\"motivo\\\":\\\"teste de falha 6\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarEmail\",\"payload\":\"{\\\"destinatario\\\":\\\"user7@email.com\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"GerarRelatorio\",\"payload\":\"{\\\"tipo\\\":\\\"Mensal\\\",\\\"formato\\\":\\\"PDF\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ProcessarPagamento\",\"payload\":\"{\\\"pedidoId\\\":\\\"ped_007\\\",\\\"valor\\\":3200.00}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarNotificacao\",\"payload\":\"{\\\"usuarioId\\\":\\\"usr_007\\\",\\\"canal\\\":\\\"sms\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ForceError\",\"payload\":\"{\\\"motivo\\\":\\\"teste de falha 7\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarEmail\",\"payload\":\"{\\\"destinatario\\\":\\\"user8@email.com\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"GerarRelatorio\",\"payload\":\"{\\\"tipo\\\":\\\"Anual\\\",\\\"formato\\\":\\\"CSV\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ProcessarPagamento\",\"payload\":\"{\\\"pedidoId\\\":\\\"ped_008\\\",\\\"valor\\\":599.90}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarNotificacao\",\"payload\":\"{\\\"usuarioId\\\":\\\"usr_008\\\",\\\"canal\\\":\\\"push\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ForceError\",\"payload\":\"{\\\"motivo\\\":\\\"teste de falha 8\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarEmail\",\"payload\":\"{\\\"destinatario\\\":\\\"user9@email.com\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"GerarRelatorio\",\"payload\":\"{\\\"tipo\\\":\\\"Semanal\\\",\\\"formato\\\":\\\"PDF\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ProcessarPagamento\",\"payload\":\"{\\\"pedidoId\\\":\\\"ped_009\\\",\\\"valor\\\":1800.00}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarNotificacao\",\"payload\":\"{\\\"usuarioId\\\":\\\"usr_009\\\",\\\"canal\\\":\\\"email\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ForceError\",\"payload\":\"{\\\"motivo\\\":\\\"teste de falha 9\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarEmail\",\"payload\":\"{\\\"destinatario\\\":\\\"user10@email.com\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"GerarRelatorio\",\"payload\":\"{\\\"tipo\\\":\\\"Diario\\\",\\\"formato\\\":\\\"Excel\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ProcessarPagamento\",\"payload\":\"{\\\"pedidoId\\\":\\\"ped_010\\\",\\\"valor\\\":2500.00}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"EnviarNotificacao\",\"payload\":\"{\\\"usuarioId\\\":\\\"usr_010\\\",\\\"canal\\\":\\\"sms\\\"}\"}"
curl -s -X POST http://localhost:8080/jobs -H "Content-Type: application/json" -d "{\"category\":\"ForceError\",\"payload\":\"{\\\"motivo\\\":\\\"teste de falha 10\\\"}\"}"
echo 50 tarefas criadas!