FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

COPY . .

RUN dotnet restore "TaskQueue.Tests/TaskQueue.Tests.csproj"

ENTRYPOINT ["dotnet", "test", "TaskQueue.Tests/TaskQueue.Tests.csproj", "--no-restore", "--logger", "console;verbosity=detailed"]